### ISSUE TITLE
[1pt] Implement rocket booking cancelation - Actions

### ISSUE THREAD

**Issue by Aquinasmoriasi** [Aquinasmoriasi/space-travelers-hub#28]
- Follow the same logic as with the "Reserve rocket" - but you need to set the `reserved` key to `false`. 
- Dispatch these actions upon click on the corresponding buttons.

**Comment by bengigo** [comment]
This issue is closed with pull request https://github.com/Aquinasmoriasi/space-travelers-hub/pull/59
